import 'package:flutter/material.dart';

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'package:cloud_firestore/cloud_firestore.dart';
import 'pages/loginPage.dart';
import 'pages/registrationPage.dart';



void firebase() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

}


// MAIN CALL TO START THE APP 
void main() {
  runApp(
    const MaterialApp(debugShowCheckedModeBanner: false, home: BasePage()),
  );
}


class BasePage extends StatefulWidget {
  const BasePage({super.key});

  @override
  State<BasePage> createState() => _BasePageState();
}

class _BasePageState extends State<BasePage> {
  int _currentIndex = 0;

  final List<Widget> _pages = const [LoginPage(), RegistrationPage()];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: IndexedStack(index: _currentIndex, children: _pages),
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: _currentIndex,
        selectedItemColor: Colors.black,
        selectedIconTheme: IconThemeData(color: Colors.blueGrey[800]),
        selectedLabelStyle: const TextStyle(fontSize: 15),
        unselectedItemColor: Colors.black,
        unselectedLabelStyle: const TextStyle(fontSize: 15),
        unselectedIconTheme: IconThemeData(color: Colors.blueGrey[800]),
        onTap: (index) {
          setState(() {
            _currentIndex = index;
          });
        },
        items: const [
          BottomNavigationBarItem(icon: Icon(Icons.login), label: "Login"),
          BottomNavigationBarItem(
            icon: Icon(Icons.app_registration),
            label: "Registration",
          ),
        ],
      ),
    );
  }
}
